language: ruby
rvm:
  - 1.9.2
  - 1.9.3
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
script: 'bundle exec rake spec'
before_script:
  - cd spec/dummy
  - RAILS_ENV=test bundle exec rake db:reset
  - bundle exec rake db:test:prepare