language: ruby
script: "bundle exec rspec"
rvm:
  - 1.9.2
  - 1.9.3
  - 1.8.7
  - ree
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
before_script:
  - cd spec/dummy
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rake db:test:prepare